@props(['title' => 'Senior Records Registry', 'eyebrow' => 'Registry Management', 'user' => ['name' => 'Maria A.', 'role' => 'OSCA Staff']])

<header x-data="{ profileOpen: false }" class="sticky top-0 z-40 flex h-[65px] items-center justify-between border-b border-slate-200 bg-white px-6 dark:border-slate-800 dark:bg-slate-900">
    <div class="min-w-0"><p class="text-[10px] font-semibold uppercase tracking-[0.16em] text-slate-500 dark:text-slate-400">{{ $eyebrow }}</p><h1 class="truncate text-lg font-bold text-slate-900 dark:text-white">{{ $title }}</h1></div>
    <div class="flex items-center gap-4">
        <span class="hidden items-center gap-2 text-xs font-medium text-slate-500 sm:flex dark:text-slate-400"><span class="h-2 w-2 rounded-full bg-emerald-500"></span>System Online</span>
        <button type="button" class="relative flex h-9 w-9 items-center justify-center rounded-lg text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800" aria-label="Notifications"><svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path stroke-linecap="round" d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></svg><span class="absolute right-1 top-1 flex h-4 min-w-4 items-center justify-center rounded-full bg-red-500 px-1 text-[9px] font-bold text-white">5</span></button>
        <button type="button" @click="darkMode = !darkMode" :aria-pressed="darkMode" aria-label="Toggle dark mode" class="flex h-9 w-9 items-center justify-center rounded-lg text-slate-500 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800"><svg x-show="!darkMode" class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path stroke-linecap="round" d="M12 3v2m0 14v2M3 12h2m14 0h2"/></svg><svg x-show="darkMode" class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path stroke-linecap="round" d="M20.5 14.5A8.5 8.5 0 0 1 9.5 3.5a8.5 8.5 0 1 0 11 11Z"/></svg></button>
        <button type="button" class="hidden items-center gap-2 rounded-xl bg-blue-600 px-4 py-2 text-xs font-bold text-white shadow-sm hover:bg-blue-700 sm:flex"><svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h2m4 0v6h-6v-3"/></svg> Scan QR</button>
        <div class="relative hidden md:block"><button type="button" @click="profileOpen = !profileOpen" class="flex items-center gap-3 border-l border-slate-200 pl-4 text-right dark:border-slate-700"><span><span class="block text-xs font-semibold text-slate-900 dark:text-white">{{ $user['name'] }}</span><span class="block text-[10px] text-slate-500 dark:text-slate-400">{{ $user['role'] }}</span></span><span class="text-xs text-slate-400">&#9662;</span></button><div x-show="profileOpen" x-cloak x-transition class="absolute right-0 top-12 w-44 rounded-xl border border-slate-200 bg-white p-2 text-left shadow-lg dark:border-slate-700 dark:bg-slate-800"><a href="#" class="block rounded-lg px-3 py-2 text-sm text-slate-600 hover:bg-slate-50 dark:text-slate-200 dark:hover:bg-slate-700">My profile</a><a href="#" class="block rounded-lg px-3 py-2 text-sm text-slate-600 hover:bg-slate-50 dark:text-slate-200 dark:hover:bg-slate-700">Sign out</a></div></div>
    </div>
</header>
