<div x-show="profileModalOpen" x-cloak class="fixed inset-0 z-[60] flex items-center justify-center overflow-y-auto bg-black/40 p-4" aria-labelledby="modal-title" role="dialog" aria-modal="true">
    <div class="relative my-auto flex max-h-[90vh] w-full max-w-4xl flex-col overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-2xl dark:bg-slate-900">
        <div class="flex-none flex items-start justify-between border-b border-slate-200 p-6 dark:border-slate-700">
            <div>
                <h2 id="modal-title" class="text-lg font-bold text-slate-900 dark:text-white" x-text="`${selectedRecord.firstName} ${selectedRecord.middleName ? selectedRecord.middleName.charAt(0) + '.' : ''} ${selectedRecord.lastName}`"></h2>
                <p class="mt-0.5 font-mono text-xs font-medium text-gray-500" x-text="selectedRecord.oscaId || 'SM-2024-0010'"></p>
            </div>
            <div class="flex items-center gap-4">
                <span class="inline-flex items-center gap-1.5 rounded-full border px-3 py-1 text-xs font-semibold" :class="{'bg-emerald-50 text-emerald-700 border-emerald-100': selectedRecord.status === 'Active', 'bg-amber-50 text-amber-700 border-amber-100': selectedRecord.status === 'Bedridden' || selectedRecord.status === 'Relocated', 'bg-purple-50 text-purple-700 border-purple-100': selectedRecord.status === 'Confined', 'bg-red-50 text-red-700 border-red-100': selectedRecord.status === 'Deceased', 'bg-gray-100 text-gray-600 border-gray-200': !['Active', 'Bedridden', 'Relocated', 'Confined', 'Deceased'].includes(selectedRecord.status)}"><span class="h-1.5 w-1.5 rounded-full" :class="{'bg-emerald-500': selectedRecord.status === 'Active', 'bg-amber-500': selectedRecord.status === 'Bedridden' || selectedRecord.status === 'Relocated', 'bg-purple-500': selectedRecord.status === 'Confined', 'bg-red-500': selectedRecord.status === 'Deceased', 'bg-gray-500': !['Active', 'Bedridden', 'Relocated', 'Confined', 'Deceased'].includes(selectedRecord.status)}"></span><span x-text="selectedRecord.status"></span></span>
                <button type="button" @click="profileModalOpen = false" aria-label="Close profile" class="text-gray-500 hover:text-gray-900"><svg class="h-6 w-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path stroke-linecap="round" d="m6 6 12 12M18 6 6 18" /></svg></button>
            </div>
        </div>

        <div class="flex-none flex gap-6 border-b border-slate-200 bg-white px-6 pt-2 dark:border-slate-700 dark:bg-slate-900">
            <button type="button" @click="activeTab = 'profile'" :class="activeTab === 'profile' ? 'border-b-2 border-blue-600 text-blue-600 font-medium' : 'text-gray-500'" class="py-3 text-sm">Profile</button>
            <button type="button" @click="activeTab = 'id_card'" :class="activeTab === 'id_card' ? 'border-b-2 border-blue-600 text-blue-600 font-medium' : 'text-gray-500'" class="py-3 text-sm">ID Card</button>
            <button type="button" @click="activeTab = 'milestone'" :class="activeTab === 'milestone' ? 'border-b-2 border-blue-600 text-blue-600 font-medium' : 'text-gray-500'" class="py-3 text-sm">Milestone &amp; Benefits</button>
        </div>

        <div class="min-h-0 flex-1 space-y-4 overflow-y-auto p-5">
            <div x-show="activeTab === 'profile'" class="flex flex-col gap-4 p-4">
                <div class="flex items-center justify-between rounded-xl border border-orange-200 bg-orange-50/50 p-4">
                    <div><p class="text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-500">Life &amp; Health Status</p><div class="mt-2 flex items-center gap-2"><span class="inline-flex items-center gap-1.5 rounded-full border px-3 py-1 text-xs font-semibold" :class="{'bg-emerald-50 text-emerald-700 border-emerald-100': selectedRecord.status === 'Active', 'bg-amber-50 text-amber-700 border-amber-100': selectedRecord.status === 'Bedridden' || selectedRecord.status === 'Relocated', 'bg-purple-50 text-purple-700 border-purple-100': selectedRecord.status === 'Confined', 'bg-red-50 text-red-700 border-red-100': selectedRecord.status === 'Deceased', 'bg-gray-100 text-gray-600 border-gray-200': !['Active', 'Bedridden', 'Relocated', 'Confined', 'Deceased'].includes(selectedRecord.status)}"><span class="h-1.5 w-1.5 rounded-full" :class="{'bg-emerald-500': selectedRecord.status === 'Active', 'bg-amber-500': selectedRecord.status === 'Bedridden' || selectedRecord.status === 'Relocated', 'bg-purple-500': selectedRecord.status === 'Confined', 'bg-red-500': selectedRecord.status === 'Deceased', 'bg-gray-500': !['Active', 'Bedridden', 'Relocated', 'Confined', 'Deceased'].includes(selectedRecord.status)}"></span><span x-text="selectedRecord.status || 'Active'"></span></span></div></div>
                    <div class="flex items-center gap-2"><button x-show="!isEditingProfile" type="button" @click="beginEditProfile()" class="rounded-xl border border-blue-200 bg-white px-3 py-2 text-sm font-semibold text-blue-700 hover:bg-blue-50">Edit Profile</button><template x-if="isEditingProfile"><div class="flex items-center gap-2"><button type="button" @click="cancelEditProfile()" class="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50">Cancel</button><button type="button" @click="saveProfile()" :disabled="!canSaveProfile" :class="canSaveProfile ? 'bg-blue-600 hover:bg-blue-700 cursor-pointer' : 'bg-blue-200 cursor-not-allowed'" class="rounded-xl px-3 py-2 text-sm font-semibold text-white">Save Changes</button></div></template></div>
                </div>

                <div x-show="!isEditingProfile" class="grid gap-3.5 md:grid-cols-2">
                    <template x-for="field in [{ label: 'Last Name', value: selectedRecord.lastName }, { label: 'First Name', value: selectedRecord.firstName }, { label: 'Middle Name', value: selectedRecord.middleName }, { label: 'Date of Birth', value: selectedRecord.birthdate || selectedRecord.dob || selectedRecord.birthDate }, { label: 'Age', value: selectedRecord.age }, { label: 'Sex', value: selectedRecord.sex }, { label: 'Barangay', value: selectedRecord.barangay }, { label: 'Street / House No.', value: selectedRecord.street || selectedRecord.homeAddress }, { label: 'Mobile Number', value: selectedRecord.mobile }, { label: 'Health / Life Status', value: selectedRecord.healthStatus || selectedRecord.status }, { label: 'OSCA ID No.', value: selectedRecord.oscaId }]" :key="field.label"><div class="rounded-xl border border-slate-200 bg-slate-50 p-3" :class="field.label === 'OSCA ID No.' ? 'col-span-1 sm:col-span-2' : ''"><p class="text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-500" x-text="field.label"></p><p class="mt-1 text-base font-bold text-slate-900" :class="field.label === 'OSCA ID No.' ? 'font-mono text-blue-600' : ''" x-text="field.value || '—'"></p></div></template>
                    <div class="col-span-1 space-y-3 rounded-2xl border border-gray-200 bg-slate-50/60 p-4 sm:col-span-2"><p class="text-[11px] font-bold uppercase tracking-wider text-slate-400">EMERGENCY CONTACT / AUTHORIZED GUARDIAN</p><div class="flex flex-col space-y-3"><div><p class="text-[11px] font-bold uppercase tracking-wider text-slate-400">CONTACT FULL NAME</p><p class="text-sm font-bold text-gray-900" x-text="selectedRecord.emergencyContact?.name || '—'"></p></div><div><p class="text-[11px] font-bold uppercase tracking-wider text-slate-400">RELATIONSHIP</p><p class="text-sm font-bold text-gray-900" x-text="selectedRecord.emergencyContact?.relationship || '—'"></p></div><div><p class="text-[11px] font-bold uppercase tracking-wider text-slate-400">CONTACT NUMBER</p><p class="text-sm font-bold text-gray-900" x-text="selectedRecord.emergencyContact?.contact || '—'"></p></div></div></div>
                    <div class="rounded-xl border border-slate-200 bg-slate-50 p-3"><p class="text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-500">Province</p><p class="mt-1 text-base font-bold text-slate-900">Bulacan</p></div><div class="rounded-xl border border-slate-200 bg-slate-50 p-3"><p class="text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-500">Municipality</p><p class="mt-1 text-base font-bold text-slate-900">Santa Maria</p></div>
                </div>

                <div x-show="isEditingProfile" class="grid gap-3.5 md:grid-cols-2">
                    <template x-for="field in [{ key: 'lastName', label: 'LAST NAME', type: 'text' }, { key: 'firstName', label: 'FIRST NAME', type: 'text' }, { key: 'middleName', label: 'MIDDLE NAME', type: 'text' }, { key: 'birthdate', label: 'DATE OF BIRTH', type: 'date' }]" :key="field.key"><div class="rounded-xl border border-slate-200 bg-slate-50 p-3"><label class="mb-1 block text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-500" x-text="field.label"></label><input x-model="editForm[field.key]" :type="field.type" class="w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 outline-none focus:border-blue-300 focus:ring-2 focus:ring-blue-100"></div></template>
                    <div class="rounded-xl border border-slate-200 bg-slate-50 p-3"><label class="mb-1 block text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-500">AGE</label><input :value="computeAge(editForm.birthdate)" type="text" readonly class="w-full rounded-lg border border-slate-200 bg-slate-100 px-3 py-2 text-sm text-slate-900 outline-none"></div>
                    <div class="rounded-xl border border-slate-200 bg-slate-50 p-3"><label class="mb-1 block text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-500">SEX</label><select x-model="editForm.sex" class="w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900"><option>Male</option><option>Female</option></select></div>
                    <div class="rounded-xl border border-slate-200 bg-slate-50 p-3"><label class="mb-1 block text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-500">BARANGAY</label><input x-model="editForm.barangay" type="text" class="w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900"></div>
                    <div class="rounded-xl border border-slate-200 bg-slate-50 p-3"><label class="mb-1 block text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-500">STREET / HOUSE NO.</label><input x-model="editForm.street" type="text" class="w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900"></div>
                    <div class="rounded-xl border border-slate-200 bg-slate-50 p-3"><label class="mb-1 block text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-500">MOBILE NUMBER</label><input x-model="editForm.mobile" type="text" class="w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900"></div>
                    <div class="rounded-xl border border-slate-200 bg-slate-50 p-3"><label class="mb-1 block text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-500">HEALTH / LIFE STATUS</label><select x-model="editForm.healthStatus" class="w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900"><option>Active</option><option>Bedridden</option><option>Confined</option><option>Relocated</option><option>Deceased</option></select></div>

                    <div x-show="editForm.healthStatus === 'Bedridden' || editForm.healthStatus === 'Confined'" class="col-span-2 space-y-3 rounded-2xl border border-orange-200 bg-orange-50/70 p-4"><div class="flex items-center gap-2 text-sm font-bold text-orange-800"><svg class="h-5 w-5 text-orange-600" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path stroke-linecap="round" d="M4 20h16M6 18V6h12v12M9 9h6M9 12h6M9 15h3" /></svg>Medical / Proxy Verification Required</div><p class="text-xs leading-relaxed text-orange-700">This status unlocks proxy claiming for LGU benefits. A guardian must present a Medical Certificate or Barangay Certificate confirming the senior's condition before the system records this change.</p><label class="flex cursor-pointer items-center gap-3 rounded-xl border border-orange-200 bg-white p-3.5"><input type="checkbox" x-model="editForm.medicalCertConfirmed" class="h-4 w-4 rounded text-orange-600 focus:ring-orange-500"><span class="text-xs font-semibold text-gray-800">Confirmed: Guardian presented a valid Medical / Barangay Certificate.</span></label></div>
                    <div x-show="editForm.healthStatus === 'Deceased'" class="col-span-2 space-y-3 rounded-2xl border border-red-200 bg-red-50/70 p-4"><div class="flex items-center gap-2 text-sm font-bold text-red-800"><svg class="h-5 w-5 text-red-600" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path stroke-linecap="round" d="M6 3h9l3 3v15H6zM15 3v4h4M9 11h6M9 15h6" /></svg>Declaration of Death — Reporting ng Patay</div><p class="text-xs leading-relaxed text-red-600">Recording this will permanently stop all future payouts and archive this record. This action cannot be undone.</p><label class="text-[11px] font-bold uppercase tracking-wider text-slate-500">DATE OF DEATH *<input type="date" x-model="editForm.dateOfDeath" class="mt-1 w-full rounded-xl border border-gray-200 bg-white px-3.5 py-2.5 text-sm text-gray-900"></label><label class="flex cursor-pointer items-center gap-3 rounded-xl border border-red-200 bg-white p-3.5"><input type="checkbox" x-model="editForm.deathCertConfirmed" class="h-4 w-4 rounded text-red-600 focus:ring-red-500"><span class="text-xs font-semibold text-gray-800">Confirmed: Guardian presented a valid Death Certificate (PSA or LCR copy).</span></label></div>

                    <div class="col-span-1 space-y-3 rounded-2xl border border-gray-200 bg-slate-50/60 p-4 sm:col-span-2"><p class="text-[11px] font-bold uppercase tracking-wider text-slate-400">EMERGENCY CONTACT / AUTHORIZED GUARDIAN</p><div class="flex flex-col space-y-3"><label><span class="text-[11px] font-bold uppercase tracking-wider text-slate-400">CONTACT FULL NAME</span><input type="text" x-model="editForm.emergencyContactName" placeholder="Full name" class="mt-1 w-full rounded-xl border border-gray-200 bg-white px-3.5 py-2 text-sm"></label><label><span class="text-[11px] font-bold uppercase tracking-wider text-slate-400">RELATIONSHIP</span><input type="text" x-model="editForm.emergencyContactRelationship" placeholder="e.g. Wife, Son, Daughter" class="mt-1 w-full rounded-xl border border-gray-200 bg-white px-3.5 py-2 text-sm"></label><label><span class="text-[11px] font-bold uppercase tracking-wider text-slate-400">CONTACT NUMBER</span><input type="text" x-model="editForm.emergencyContactNumber" placeholder="09XX XXX XXXX" class="mt-1 w-full rounded-xl border border-gray-200 bg-white px-3.5 py-2 text-sm"></label></div></div>
                    <div class="col-span-1 rounded-xl border border-slate-200 bg-slate-50 p-3 sm:col-span-2"><label class="mb-1 block text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-500">OSCA ID NO.</label><input :value="editForm.oscaId" readonly class="w-full rounded-lg border border-slate-200 bg-slate-100 px-3 py-2 font-mono text-sm text-blue-600"></div><div class="rounded-xl border border-slate-200 bg-slate-50 p-3"><p class="text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-500">PROVINCE / MUNICIPALITY</p><p class="mt-2 text-sm font-bold text-slate-900">Bulacan / Santa Maria</p></div>
                </div>
            </div>

            <div x-show="activeTab === 'id_card'" class="space-y-4 p-6">
                <div class="rounded-2xl border-2 border-gray-300 bg-white p-5 text-gray-900 shadow-md"><div class="border-b border-gray-300 pb-2 text-center"><h4 class="text-xs font-extrabold uppercase tracking-tight text-gray-950">SENIOR CITIZEN IDENTIFICATION CARD</h4><p class="text-[10px] text-gray-700">Republic of the Philippines</p></div><div class="grid gap-4 py-5 sm:grid-cols-[120px_1fr]"><div class="flex h-32 items-center justify-center rounded-xl bg-slate-100 text-xs text-slate-500">OSCA ID PHOTO</div><div class="space-y-2 text-sm"><p><span class="font-bold">Name:</span> <span x-text="`${selectedRecord.firstName || ''} ${selectedRecord.lastName || ''}`"></span></p><p><span class="font-bold">OSCA ID:</span> <span class="font-mono text-blue-600" x-text="selectedRecord.oscaId || ''"></span></p><p><span class="font-bold">Barangay:</span> <span x-text="selectedRecord.barangay || ''"></span></p></div></div><div class="grid grid-cols-2 gap-4 border-t border-gray-300 pt-3 text-center text-[10px]"><div><div class="border-t border-gray-400 pt-1 font-bold">CARDHOLDER SIGNATURE</div></div><div><div class="border-t border-gray-400 pt-1 font-bold">OSCA HEAD</div></div></div></div><button type="button" class="w-full max-w-[420px] rounded-xl bg-blue-600 px-6 py-3 font-bold text-white"><svg class="mr-2 inline h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path stroke-linecap="round" d="M12 3v12m0 0 4-4m-4 4-4-4M5 21h14" /></svg>Download Digital ID (PDF)</button>
            </div>

            <div x-show="activeTab === 'milestone'" class="p-6"><p class="mb-3 text-xs font-semibold uppercase tracking-wider text-gray-500">Milestone Timeline</p><div class="space-y-4 border-l-2 border-gray-200 pl-3"><div class="relative rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm"><span class="absolute -left-[1.35rem] top-3 h-3 w-3 rounded-full bg-blue-600 ring-4 ring-white"></span><b class="text-blue-600">60+ Active Senior</b><span class="block text-slate-500">Registered in eLINGAP registry; entitled to all senior discounts under R.A. 9994.</span></div><div class="relative rounded-xl border border-gray-200 p-4 text-sm"><span class="absolute -left-[1.35rem] top-4 h-3 w-3 rounded-full border-2 border-gray-300 bg-white"></span><b>80+ Cash Gift</b><span class="block text-slate-500">Entitled to statutory cash gift from the municipal government upon reaching age 80.</span></div><div class="relative rounded-xl border border-gray-200 p-4 text-sm"><span class="absolute -left-[1.35rem] top-4 h-3 w-3 rounded-full border-2 border-gray-300 bg-white"></span><b>90+ Cash Gift</b><span class="block text-slate-500">Entitled to statutory cash gift upon reaching age 90.</span></div></div></div>
        </div>
    </div>
</div>
