@extends('layouts.app', ['title' => 'Messaging | GabayDocs', 'active' => 'Messaging', 'headerTitle' => 'Messaging', 'headerEyebrow' => 'SMS Center & Alerts'])

@section('content')
<div x-data="{ historyModalOpen: false, selectedBarangay: 'All Barangays', selectedStatus: 'All Seniors', activeTemplate: '', messageText: '', templates: { 'Payout Rescheduled': 'Abiso: Ang scheduled payout para bukas ay ipinagpaliban dahil sa malakas na ulan at baha. Abisuhan kayo sa bagong petsa. — OSCA Santa Maria', 'Office Closed': 'Abiso: Ang OSCA Santa Maria office ay sarado bukas para sa LGU holiday. Magbubukas muli sa susunod na araw ng trabaho. Salamat.', 'Bring Physical ID': 'Paalala: Mangyaring dalhin ang inyong pisikal na OSCA ID card kapag pumunta upang kunin ang inyong pension. Kinakailangan para sa pagpapalaya ng pondo.', 'Payout Tomorrow': 'Paalala: Ang pagbabayad ng pension ay bukas. Pumunta sa [LUGAR] sa pagitan ng 8:00 AM at 4:00 PM. Dalhin ang OSCA ID at valid ID. — OSCA Santa Maria', 'Free Medical Check-up': 'Imbitasyon: Libreng medical check-up bukas sa [LUGAR], 8AM–12NN. Dalhin ang OSCA ID. — OSCA Santa Maria' }, broadcastHistory: [{ barangay: 'All Barangays', status: 'All Seniors', date: 'Oct 3, 2026 8:00 AM', message: 'Paalala: Ang pagbabayad ng pension ay bukas. Pumunta sa Santa Maria Municipal Gymnasium sa pagitan ng 8:00 AM at 4:00 PM. Dalhin ang OSCA ID at valid ID. — OSCA Santa Maria', sentCount: 7, failedCount: 1, showFailed: false, failedRecipients: [{ name: 'Gomez, Florentino A.', phone: '09311234567' }] }, { barangay: 'Poblacion', status: 'All Seniors', date: 'Oct 1, 2026 10:30 AM', message: 'Imbitasyon: Libreng medical check-up bukas sa Poblacion Barangay Hall, 8AM–12NN. Dalhin ang OSCA ID. — OSCA Santa Maria', sentCount: 5, failedCount: 0, showFailed: false, failedRecipients: [] }, { barangay: 'All Barangays', status: 'Active', date: 'Sep 30, 2026 3:00 PM', message: 'Abiso: Ang OSCA Santa Maria office ay sarado bukas para sa LGU holiday. Magbubukas muli sa susunod na araw ng trabaho. Salamat.', sentCount: 8, failedCount: 0, showFailed: false, failedRecipients: [] }], sendBroadcast() { this.broadcastHistory.unshift({ barangay: this.selectedBarangay, status: this.selectedStatus, date: new Date().toLocaleString('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' }), message: this.messageText, sentCount: 7, failedCount: 1, showFailed: false, failedRecipients: [{ name: 'Gomez, Florentino A.', phone: '09311234567' }] }); this.messageText = ''; this.activeTemplate = ''; this.historyModalOpen = true; } }" class="min-h-[calc(100vh-65px)] bg-slate-50 px-6 pb-8 pt-8 dark:bg-slate-950">
    <div class="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><p class="text-sm text-gray-500">Compose and send broadcast announcements to senior citizens by barangay or status group.</p><button type="button" @click="historyModalOpen = true" class="inline-flex cursor-pointer items-center gap-2 rounded-xl border border-gray-200 bg-white px-4 py-2.5 text-sm font-medium text-gray-800 shadow-sm transition-all hover:bg-gray-50 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200"><svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><circle cx="12" cy="12" r="8"/><path stroke-linecap="round" d="M12 8v4l2.5 2"/></svg>View Broadcast History</button></div>
    @include('components.messaging-compose')
    @include('components.messaging-history')
</div>
@endsection
